/**
 * SAP Consultant Workspace — DOCX Export Script
 * Cross-platform (Windows + MacOS), multi-language (ES/EN).
 *
 * Usage: node export.js <path-to-json>
 * 
 * Resolves the 'docx' dependency from the skill's own node_modules
 * (installed during install.js), NOT the user's CWD.
 */

const fs = require('fs');
const path = require('path');

// Resolve docx from the skill's package, not CWD
const skillRoot = path.resolve(__dirname, '..', '..', '..');
const possibleDocxPaths = [
    path.join(skillRoot, 'node_modules', 'docx'),
    path.join(__dirname, '..', 'node_modules', 'docx'),
    'docx'  // fallback to global/CWD
];

let docx;
for (const docxPath of possibleDocxPaths) {
    try {
        docx = require(docxPath);
        break;
    } catch (e) { /* try next */ }
}

if (!docx) {
    console.error('❌ Error: "docx" library not found.');
    console.error('   Run: npm install docx');
    console.error('   Or re-run the installer: node install.js');
    process.exit(1);
}

const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = docx;

// --- i18n labels ---
const LABELS = {
    es: {
        title_adr: 'Registro de Decisión Arquitectónica (ADR)',
        titleLabel: 'Título',
        clientLabel: 'Cliente',
        dateLabel: 'Fecha',
        context: '1. Contexto',
        options: '2. Opciones Consideradas',
        pros: 'Pros:',
        cons: 'Contras:',
        recommendation: '3. Recomendación Arquitectónica',
        consequences: '4. Consecuencias',
        noContext: 'Sin contexto provisto.',
        pending: 'Pendiente.',
        footer: 'Generado por SAP Consultant AI Workspace'
    },
    en: {
        title_adr: 'Architecture Decision Record (ADR)',
        titleLabel: 'Title',
        clientLabel: 'Client',
        dateLabel: 'Date',
        context: '1. Context',
        options: '2. Options Considered',
        pros: 'Pros:',
        cons: 'Cons:',
        recommendation: '3. Architectural Recommendation',
        consequences: '4. Consequences',
        noContext: 'No context provided.',
        pending: 'Pending.',
        footer: 'Generated by SAP Consultant AI Workspace'
    }
};

// --- Main ---
const jsonPath = process.argv[2];

if (!jsonPath) {
    console.error('❌ Usage: node export.js <path-to-json>');
    process.exit(1);
}

const resolvedPath = path.resolve(jsonPath);
if (!fs.existsSync(resolvedPath)) {
    console.error(`❌ Error: File not found: ${resolvedPath}`);
    process.exit(1);
}

let adrData;
try {
    adrData = JSON.parse(fs.readFileSync(resolvedPath, 'utf-8'));
} catch (e) {
    console.error(`❌ Error parsing JSON: ${e.message}`);
    process.exit(1);
}

const lang = (adrData.language || 'es').toLowerCase();
const L = LABELS[lang] || LABELS.es;

function createADRDocument(data) {
    const children = [];

    // Document title
    children.push(new Paragraph({
        text: L.title_adr,
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 }
    }));

    // Metadata
    children.push(new Paragraph({
        children: [
            new TextRun({ text: `${L.titleLabel}: `, bold: true }),
            new TextRun(data.title || 'ADR'),
        ],
        spacing: { after: 120 }
    }));
    children.push(new Paragraph({
        children: [
            new TextRun({ text: `${L.clientLabel}: `, bold: true }),
            new TextRun(data.client || '-'),
        ],
        spacing: { after: 120 }
    }));
    children.push(new Paragraph({
        children: [
            new TextRun({ text: `${L.dateLabel}: `, bold: true }),
            new TextRun(data.date || new Date().toISOString().split('T')[0]),
        ],
        spacing: { after: 300 }
    }));

    // Context
    children.push(new Paragraph({ text: L.context, heading: HeadingLevel.HEADING_1 }));
    children.push(new Paragraph({ text: data.context || L.noContext, spacing: { after: 300 } }));

    // Options
    children.push(new Paragraph({ text: L.options, heading: HeadingLevel.HEADING_1 }));
    (data.options || []).forEach((opt, idx) => {
        children.push(new Paragraph({
            text: `${idx + 1}. ${opt.name}`,
            heading: HeadingLevel.HEADING_2
        }));

        children.push(new Paragraph({
            children: [new TextRun({ text: L.pros, bold: true })],
            spacing: { before: 100 }
        }));
        (opt.pros || []).forEach(p => {
            children.push(new Paragraph({
                text: `  • ${p}`,
                spacing: { after: 40 }
            }));
        });

        children.push(new Paragraph({
            children: [new TextRun({ text: L.cons, bold: true })],
            spacing: { before: 100 }
        }));
        (opt.cons || []).forEach(c => {
            children.push(new Paragraph({
                text: `  • ${c}`,
                spacing: { after: 40 }
            }));
        });
        children.push(new Paragraph({ text: ' ', spacing: { after: 200 } }));
    });

    // Recommendation
    children.push(new Paragraph({ text: L.recommendation, heading: HeadingLevel.HEADING_1 }));
    children.push(new Paragraph({ text: data.recommendation || L.pending, spacing: { after: 300 } }));

    // Technical Design (New for V3.1)
    if (data.technicalDesign && data.technicalDesign.objects) {
        children.push(new Paragraph({ text: lang === 'es' ? '4. Diseño Técnico' : '4. Technical Design', heading: HeadingLevel.HEADING_1 }));
        
        data.technicalDesign.objects.forEach(obj => {
            children.push(new Paragraph({
                children: [
                    new TextRun({ text: `${obj.type}: `, bold: true }),
                    new TextRun({ text: obj.name, color: '005483', bold: true })
                ],
                heading: HeadingLevel.HEADING_2
            }));
            
            if (obj.package) {
                children.push(new Paragraph({
                    children: [new TextRun({ text: `Package: ${obj.package}`, italic: true })]
                }));
            }
            
            children.push(new Paragraph({ text: obj.description || '', spacing: { after: 120 } }));
            
            if (obj.code) {
                children.push(new Paragraph({
                    children: [new TextRun({ 
                        text: obj.code, 
                        font: 'Courier New', 
                        size: 16,
                        color: '333333'
                    })],
                    shading: { fill: 'F4F4F4' },
                    spacing: { before: 200, after: 200 }
                }));
            }
        });
    }

    // Consequences
    children.push(new Paragraph({ text: L.consequences, heading: HeadingLevel.HEADING_1 }));
    (data.consequences || []).forEach(c => {
        children.push(new Paragraph({
            text: `  • ${c}`,
            spacing: { after: 40 }
        }));
    });

    // Footer
    children.push(new Paragraph({
        text: '',
        spacing: { before: 600 }
    }));
    children.push(new Paragraph({
        children: [new TextRun({ text: L.footer, italics: true, size: 18, color: '888888' })],
        alignment: AlignmentType.CENTER,
    }));

    return new Document({
        creator: 'SAP Consultant AI Workspace',
        title: data.title || 'ADR',
        sections: [{ properties: {}, children }]
    });
}

const doc = createADRDocument(adrData);
const safeTitle = (adrData.title || 'Report').replace(/[^a-z0-9]/gi, '_').substring(0, 50);
const outputPath = path.join(path.dirname(resolvedPath), `ADR_${safeTitle}.docx`);

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync(outputPath, buffer);
    console.log(`\n✅ DOCX generated: ${outputPath}`);
}).catch(err => {
    console.error(`❌ Error generating DOCX: ${err.message}`);
    process.exit(1);
});
